### ISSUE TITLE
Extending a goss.yaml, but `gossfile` is always relative

### ISSUE THREAD

**Issue by bryanlatten** [aelsabbahy/goss#144] opened 2016-09-02 14:47 UTC
From the file `/example/goss.yaml`

```
gossfile:
  /differentexample/extendme.yaml: {}
```

Produces: 
```File error: open /example/differentexample/extendme.yaml: no such file or directory```

Expected: `extendme.yaml` would be picked up from the `/differentexample` folder

**Comment by aelsabbahy** [comment] 2016-09-06 18:12
Marking this as a duplicate of #137, the issue has been resolved by #138 and should be released by the end of the week.

I'll update/close this issue when it's released.

**Comment by aelsabbahy** [comment] 2016-09-28 13:03
Fixed in [v0.2.4](https://github.com/aelsabbahy/goss/releases/tag/v0.2.4)

**Closed by aelsabbahy** 2016-09-28 13:03 UTC
Labels: duplicate
