### ISSUE TITLE
is there any way to test if condition?

### ISSUE THREAD

**Issue by dhajoshi** [aelsabbahy/goss#178] opened 2016-11-30 10:55 UTC
hello,

i am using goss, but i have requirement where i have different regions and they have different settings let say timezone, so how do i check if my region is "this" it should be "this" timezone.

i know i can write shell script and run that as command but just want to know if any way to make it better?

Thanks,
DJ

**Comment by aelsabbahy** [comment] 2016-12-05 23:17
I think this is related to https://github.com/aelsabbahy/goss/issues/136#issuecomment-242773611

I haven't gotten around to implementing that feature. Let me know if that feature would cover your needs and I'll mark this issue as a duplicate.

**Comment by dhajoshi** [comment] 2016-12-07 17:37
yes, it should cover my needs, so you can get the value of variables from facter and then make some decision on result ... what you think how difficult to implement this ? actually i dont have any expertise in GO or i will be happy to contribute.. :(

**Comment by aelsabbahy** [comment] 2016-12-08 00:30
I don't think it's very difficult to implement. Unfortunately, I haven't had a lot of free time as of late to do this.

I'm going to close this as a duplicate of #136

**Closed by aelsabbahy** 2016-12-08 00:30 UTC

**Comment by aelsabbahy** [comment] 2017-03-06 15:02
Released in [v0.3.0](https://github.com/aelsabbahy/goss/releases/tag/v0.3.0)
