### ISSUE TITLE
Dgoss no longer working in linux docker images, throws bad interpreter error.

### ISSUE THREAD

**Issue by treacher** [aelsabbahy/goss#595] opened 2020-06-22 23:40 UTC
**Describe the bug**
dgoss is not working when running within a RHEL7 docker container. (I suspect maybe it's not compiled for the right architecture)

**How To Reproduce**
1. Run a centos docker image
2. Download dgoss into the image
3. Run dgoss

**Expected Behavior**
Expected the following output when running dgoss in a linux docker container:
```
sh-4.2# dgoss
ERROR: USAGE: dgoss [run|edit] <docker_run_params>
```

**Actual Behavior**
dgoss produces the following error:
```
sh: /usr/local/bin/dgoss: /bin/bash^M: bad interpreter: No such file or directory
```

**Environment:**
 - 0.3.12
 - RHEL7 Docker Image

This was previously working in version `0.3.10`

**Comment by aelsabbahy** [comment] 2020-06-22 23:53
dgoss is a shell script.. not compiled.

When I curl it into a centos container I'm not seeing any windows newline issues.

Can you send the exact steps you did to reproduce this? Looks like a windows newline possibly in the file?

**Comment by aelsabbahy** [comment] 2020-06-22 23:57
Here's what I did to test.

```
docker run --rm -it centos:7 sh
sh-4.2# yum install -y which > /dev/null 2>&1
sh-4.2# curl -fsSL https://goss.rocks/install | sh
Downloading https://github.com/aelsabbahy/goss/releases/download/v0.3.12/goss-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   627  100   627    0     0   1303      0 --:--:-- --:--:-- --:--:--  1303
100 11.6M  100 11.6M    0     0  2988k      0  0:00:04  0:00:04 --:--:-- 4116k
Goss v0.3.12 has been installed to /usr/local/bin/goss
goss --version
goss version v0.3.12
Downloading https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4289  100  4289    0     0  19707      0 --:--:-- --:--:-- --:--:-- 19674
dgoss master has been installed to /usr/local/bin/dgoss
sh-4.2# dgoss
ERROR: USAGE: dgoss [run|edit] <docker_run_params>
```

**Comment by aelsabbahy** [comment] 2020-06-22 23:58
Oh wait, I think I know what's causing this. The windows build that was added to goss.

@petemounce Do you know how to make sure that the dgoss that gets uploaded is from the linux machine and not the windows one?

**Comment by treacher** [comment] 2020-06-23 00:07
Sweet, I managed to get a better way to reproduce the issue:

Dockerfile:
```
FROM registry.access.redhat.com/rhel7

ARG GOSS_SLEEP=2.0
ENV GOSS_FILES_STRATEGY=cp

RUN cd /tmp && curl -LO https://download.docker.com/linux/static/stable/x86_64/docker-19.03.11.tgz && \
            tar -xzvf docker-19.03.11.tgz && \
            chmod +x docker/docker && \
            mv docker/docker /usr/local/bin/ && \
            rm -rf docker*

ADD https://github.com/aelsabbahy/goss/releases/download/v0.3.12/goss-linux-amd64 /usr/local/bin/goss
ADD https://github.com/aelsabbahy/goss/releases/download/v0.3.12/dgoss /usr/local/bin/dgoss

RUN chmod +x /usr/local/bin/dgoss /usr/local/bin/goss
```

Then run the following with this docker image:
```
docker build . -t dgoss-test-issue:latest
docker run dgoss-test-issue:latest dgoss
```

**Comment by aelsabbahy** [comment] 2020-06-23 00:46
Should be fixed in v0.3.13, let me know if it's not and I'll re-open the ticket.

Thanks for reporting this.

**Comment by aelsabbahy** [comment] 2020-06-23 00:48
@petemounce I added a conditional on the deployment, it was a quick hack to get this working without removing windows out.

I think the better long term fix would be to migrate to multi-stage travis builds.

**Closed** 2020-06-23 00:47 UTC
Labels: bug

**Comment by treacher** [comment] 2020-06-23 00:49
Thanks for the rapid response! It's working now, cheers!
