### ISSUE TITLE
sh: 1: goss: not found

### ISSUE THREAD

**Issue by slecache** [aelsabbahy/goss#389] opened 2018-09-21 22:12 UTC
Environment:
- OS: Windows 10
- Docker Engine: Docker4Windows with "expose deamon on tcp://localhost:2375 without TLS" option checked
- Docker client with Windows Subsystem for Linux
- goss installed with Windows Subsystem for Linux

When I try `dgoss edit -p 8080:80 nginx:1.11.1` I get the following error:
```
INFO: Starting docker container
INFO: Container ID: ffdde748
INFO: Run goss add/autoadd to add resources
# goss
sh: 1: goss: not found
#
```

**Comment by edyan** [comment] 2018-09-23 14:07
Hi, make sure bash is installed (the dgoss interpreter is bash)

Or try to verify : `sh dgoss edit -p 8080:80 nginx:1.11.1` and `bash dgoss edit -p 8080:80 nginx:1.11.1`

**Comment by slecache** [comment] 2018-09-24 07:03
Hi,

Bash is installed and it is the default shell interpreter:
```shell
$ ps -p $$ | awk '$1 != "PID" {print $(NF)}'
ps -p $$ | awk '$1 != "PID" {print $(NF)}'
bash

$ bash --version
bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Starting with `sh` failed:
```shell
$ cd $(dirname `which dgoss`) && sh dgoss edit -p 8080:80 nginx:1.11.1
dgoss: 71: dgoss: [[: not found
-e ERROR: Couldn't find goss installation, please set GOSS_PATH to it
dgoss: 20: dgoss: [[: not found
```
And got the same error as before by forcing `bash`. `goss` seems to be missing (in the temporary container?):
```shell
$ cd $(dirname `which dgoss`) && bash dgoss edit -p 8080:80 nginx:1.11.1
INFO: Starting docker container
INFO: Container ID: a90bac77
INFO: Run goss add/autoadd to add resources
# goss a file /var/log/nginx/access.log /var/log/nginx/error.log
sh: 1: goss: not found
#
```

**Comment by edyan** [comment] 2018-09-29 22:48
Hi, if i run the command under linux I have no problem so I believe it's related to windows.

The only thing I know is that goss is mounted in `/goss/goss` you can try then `/goss/goss a file ...`

 I personnaly, can't help. Good luck !

**Comment by justinschmitt** [comment] 2018-11-14 01:15
I'm experiencing the same issue with the same development environment.  I think it's a WSL specific issue.

**Comment by SimonBaeumer** [comment] 2018-12-11 13:59
The problem is that `dgoss` wants to mount a directory into your container from another container. This gives problems with the filesystem `overflayfs` used by docker.

You can find a little bit more information in this article in the section `the ugly`.
[Using Docker-in-Docker](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

**Comment by syednadeembe** [comment] 2019-01-18 07:54
My environment is linux and i get the same problem.

I'm following along this link: https://medium.com/@aelsabbahy/tutorial-how-to-test-your-docker-image-in-half-a-second-bbd13e06a4a9

goss a file /var/log/nginx/access.log /var/log/nginx/error.log is what I'm pasting in the interactive shell and the following error is displayed

/goss/goss: 1: /goss/goss: Not: not found

**Comment by aelsabbahy** [comment] 2019-01-19 15:21
dgoss uses mount by default, but can be changed to cp, you'll lose some functionality, but it's needed in some cases.
Try setting [GOSS_FILE_STRATEGY](https://github.com/aelsabbahy/goss/blob/master/extras/dgoss/README.md#goss_files_strategy) to cp.

Also, on non-linux systems you have to define GOSS_PATH pointing it to the full path of the goss executable.

Here's a list of all variables and their defaults, you can also look at dgoss code (~100 lines of bash) to get a closer look at what each of those vars do.
https://github.com/aelsabbahy/goss/tree/master/extras/dgoss#environment-vars-and-defaults

**Comment by syednadeembe** [comment] 2019-01-20 03:30
How do I have to set GOSS_FILE_STRATEGY to cp ?

This is how my environment looks like: 
--I have docker demon running on a linux VM.
--On this VM I Installed goss/dgoss
--I tried export GOSS_FILES_STRATEGY=cp on the VM
--Then executed dgoss edit -p 8080:80 nginx:1.11.10x
--Now I'm logged into the interactive shell, writting goss a file /var/log/nginx/access.log /var/log/nginx/error.log gives me the error.

export GOSS_FILES_STRATEGY=cp is what I'm doing on the VM where the docker demon is running but that not resolving the problem,

**Comment by syednadeembe** [comment] 2019-01-20 03:46
I also tried to set this value directly in the dgoss file. ( this file on my VM, see above comment for setup details )

Did the following for reference:
[saguser@vmmosy08 bin]$ which goss
/usr/local/bin/goss
[saguser@vmmosy08 bin]$ which dgoss
/usr/local/bin/dgoss

[saguser@vmmosy08 bin]$ cat /usr/local/bin/goss
Not Found[saguser@vmmosy08 bin]$

[saguser@vmmosy08 bin]$ vi /usr/local/bin/dgoss
//Manually set GOSS_FILES_STRATEGY=cp

**Closed** 2019-12-12 08:42 UTC
